"""Generate Python workflow harness files from declarative step specs.

Input: a dict with id, name, trigger_type, and steps list.
Output: a valid Python source string following the harness pattern.
"""

from __future__ import annotations

import keyword
import re
import textwrap
from pathlib import Path
from typing import Any, Dict, List

from workflow.harnesses import _BUILTIN_IDS, _ensure_loaded, _get_custom_dir

_ID_RE = re.compile(r"^[a-z][a-z0-9-]{1,58}[a-z0-9]$")
_STEP_TYPES = {"shell", "http", "file_write", "event", "python"}


def validate_spec(spec: Dict[str, Any]) -> List[str]:
    """Validate a harness spec dict. Returns list of error strings (empty = valid)."""
    _ensure_loaded()
    errors = []

    hid = spec.get("id", "")
    if not _ID_RE.match(hid):
        errors.append(f"id must be kebab-case, 3-60 chars: got {hid!r}")
    if hid in _BUILTIN_IDS:
        errors.append(f"id '{hid}' collides with a built-in harness")

    if not spec.get("name", "").strip():
        errors.append("name is required")

    trigger = spec.get("trigger_type", "")
    if trigger not in ("cron", "manual", "file_watch"):
        errors.append(f"trigger_type must be cron, manual, or file_watch: got {trigger!r}")

    steps = spec.get("steps", [])
    if not steps:
        errors.append("at least one step is required")

    seen_names = set()
    for i, step in enumerate(steps):
        sname = step.get("name", "")
        if not sname.isidentifier() or keyword.iskeyword(sname):
            errors.append(f"step[{i}].name must be a valid Python identifier: got {sname!r}")
        if sname in seen_names:
            errors.append(f"step[{i}].name '{sname}' is a duplicate")
        seen_names.add(sname)

        stype = step.get("type", "")
        if stype not in _STEP_TYPES:
            errors.append(f"step[{i}].type must be one of {_STEP_TYPES}: got {stype!r}")

        cfg = step.get("config", {})
        if stype == "shell" and not cfg.get("command"):
            errors.append(f"step[{i}] (shell): command is required")
        if stype == "http" and not cfg.get("url"):
            errors.append(f"step[{i}] (http): url is required")
        if stype == "file_write" and not cfg.get("path"):
            errors.append(f"step[{i}] (file_write): path is required")
        if stype == "event" and not cfg.get("event_type"):
            errors.append(f"step[{i}] (event): event_type is required")

        if stype == "python":
            code = cfg.get("code", "")
            if not code.strip():
                errors.append(f"step[{i}] (python): code is required")
            else:
                try:
                    compile(code, f"<step:{sname}>", "exec")
                except SyntaxError as e:
                    errors.append(f"step[{i}] (python): syntax error: {e}")

    return errors


def generate_source(spec: Dict[str, Any]) -> str:
    """Generate a complete Python harness file from a validated spec."""
    hid = spec["id"]
    name = spec["name"]
    trigger = spec["trigger_type"]
    steps = spec["steps"]

    parts = []

    # Module docstring
    step_summary = "\n".join(f"  {i+1}. {s['name']}" for i, s in enumerate(steps))
    parts.append(f'"""Custom harness: {hid}\n\n{name}\n\nSteps:\n{step_summary}\n\nGenerated by the Hermes dashboard harness creator.\n"""')

    # Imports
    parts.append(textwrap.dedent("""\
        from __future__ import annotations

        import json
        import logging
        import subprocess
        import urllib.request
        from pathlib import Path
        from typing import Any, Dict

        from workflow.primitives import StepDef, WorkflowDef

        logger = logging.getLogger(__name__)
    """))

    # Step functions
    for step in steps:
        parts.append(_generate_step_function(step))

    # WORKFLOW definition
    step_defs = []
    for step in steps:
        timeout = step.get("timeout_s", 600)
        skip = step.get("skip_on_error", False)
        step_defs.append(
            f'        StepDef(name="{step["name"]}", fn={step["name"]}, '
            f'timeout_s={timeout}, skip_on_error={skip}),'
        )

    trigger_meta = "{}"
    parts.append(textwrap.dedent(f"""\
        # ---------------------------------------------------------------------------
        # Workflow definition
        # ---------------------------------------------------------------------------

        WORKFLOW = WorkflowDef(
            id="{hid}",
            name="{name}",
            trigger_type="{trigger}",
            steps=[
        {chr(10).join(step_defs)}
            ],
            trigger_meta={trigger_meta},
        )
    """))

    return "\n\n".join(parts)


def _generate_step_function(step: Dict[str, Any]) -> str:
    """Generate a single step function."""
    sname = step["name"]
    stype = step["type"]
    cfg = step.get("config", {})

    header = f'def {sname}(ctx: Dict[str, Any]) -> Dict[str, Any]:\n    """Step: {sname} ({stype})."""'

    if stype == "shell":
        cmd = cfg["command"].replace('"', '\\"')
        body = (
            f'command = "{cmd}"\n'
            f'logger.info("Running: %s", command)\n'
            f'result = subprocess.run(\n'
            f'    command, shell=True, capture_output=True, text=True, timeout=300\n'
            f')\n'
            f'return {{\n'
            f'    "stdout": result.stdout,\n'
            f'    "stderr": result.stderr,\n'
            f'    "returncode": result.returncode,\n'
            f'}}'
        )

    elif stype == "http":
        url = cfg["url"].replace('"', '\\"')
        method = cfg.get("method", "GET").upper()
        body_data = cfg.get("body", "")
        if body_data:
            body_data_escaped = body_data.replace('"', '\\"')
            body = textwrap.dedent(f"""\
                url = "{url}"
                logger.info("{method} %s", url)
                data = "{body_data_escaped}".encode("utf-8")
                req = urllib.request.Request(url, data=data, method="{method}")
                req.add_header("Content-Type", "application/json")
                with urllib.request.urlopen(req, timeout=30) as resp:
                    raw = resp.read().decode("utf-8")
                    try:
                        parsed = json.loads(raw)
                    except json.JSONDecodeError:
                        parsed = None
                    return {{"status": resp.status, "body": raw, "json": parsed}}""")
        else:
            body = textwrap.dedent(f"""\
                url = "{url}"
                logger.info("{method} %s", url)
                req = urllib.request.Request(url, method="{method}")
                with urllib.request.urlopen(req, timeout=30) as resp:
                    raw = resp.read().decode("utf-8")
                    try:
                        parsed = json.loads(raw)
                    except json.JSONDecodeError:
                        parsed = None
                    return {{"status": resp.status, "body": raw, "json": parsed}}""")

    elif stype == "file_write":
        path = cfg["path"].replace('"', '\\"')
        content_key = cfg.get("content_from_ctx", "")
        if content_key:
            body = textwrap.dedent(f"""\
                path = Path("{path}")
                content = str(ctx.get("{content_key}", {{}}))
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
                logger.info("Wrote %d bytes to %s", len(content), path)
                return {{"path": str(path), "bytes_written": len(content)}}""")
        else:
            content = cfg.get("content", "").replace('"', '\\"')
            body = textwrap.dedent(f"""\
                path = Path("{path}")
                content = "{content}"
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
                logger.info("Wrote %d bytes to %s", len(content), path)
                return {{"path": str(path), "bytes_written": len(content)}}""")

    elif stype == "event":
        event_type = cfg["event_type"].replace('"', '\\"')
        data = cfg.get("data", "{}").replace('"', '\\"')
        body = textwrap.dedent(f"""\
            from gateway.event_bus import get_event_bus
            bus = get_event_bus()
            event_data = json.loads("{data}")
            bus.publish("{event_type}", event_data)
            logger.info("Published event: {event_type}")
            return {{"published": True, "event_type": "{event_type}"}}""")

    elif stype == "python":
        code = cfg["code"]
        # Indent the user code by 4 spaces for the function body
        indented = textwrap.indent(code.strip(), "    ")
        body = indented

    else:
        body = '    return {"error": "unknown step type"}'

    if stype == "python":
        return f"{header}\n{body}"
    # Indent the body by 4 spaces for the function
    indented_body = textwrap.indent(body, "    ")
    return f"{header}\n{indented_body}"


def write_harness(spec: Dict[str, Any]) -> Path:
    """Validate spec, generate Python source, write to custom harnesses dir.

    Returns the path to the written file.
    Raises ValueError if validation fails.
    """
    errors = validate_spec(spec)
    if errors:
        raise ValueError("Harness spec validation failed:\n" + "\n".join(f"  - {e}" for e in errors))

    source = generate_source(spec)
    filename = spec["id"].replace("-", "_") + ".py"
    out_path = _get_custom_dir() / filename
    out_path.write_text(source, encoding="utf-8")
    return out_path
